jwt:
  secret: ==========================secret==========================
  lifetime: 7d

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://amazon-postgres:5432/amazon_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/reports?authSource=admin
    redis:
      host: redis
      port: 6379
    cache:
      type: redis

logging:
  level:
    org:
      springframework:
        security: DEBUG
        sql: DEBUG
        jdbc: DEBUG